### ISSUE TITLE
Error running demo dataset - .onLoad failed in loadNamespace() for 'shiny'

### ISSUE THREAD

**Issue by marcDabad** [gagneurlab/drop#1]
Hi, 

When I am trying to run this pipeline with demo datasets I have this problem:

```
[Fri Jan 10 14:34:44 2020]
rule Scripts_Outrider_Summary_R:
    input: demo/Output/processed_results/aberrant_expression/v29/outrider/outrider/ods.Rds, demo/Output/processed_results/aberrant_expression/v29/outrider/outrider/OUTRIDER_results.tsv, Scripts/Outrider/Summary.R
    output: demo/Output/htmlOutput/AberrantExpression/Outrider/v29/Summary_outrider.html
    jobid: 9
    wildcards: annotation=v29, dataset=outrider

Loading required package: knitr
Loading required package: rmarkdown
[1] TRUE


processing file: /scratch_tmp/19940125/RtmpFkh6vQ/file5eb9168ca90c/Summary.spin.Rmd
  |....                                                                                                          |   4%
   inline R code fragments

  |........                                                                                                      |   8%
label: unnamed-chunk-1 (with options) 
List of 1
 $ echo: symbol F

  |.............                                                                                                 |  12%
  ordinary text without R code

  |.................                                                                                             |  15%
label: unnamed-chunk-2
  |.....................                                                                                         |  19%
   inline R code fragments

  |.........................                                                                                     |  23%
label: unnamed-chunk-3
  |..............................                                                                                |  27%
  ordinary text without R code

  |..................................                                                                            |  31%
label: unnamed-chunk-4
  |......................................                                                                        |  35%
  ordinary text without R code

  |..........................................                                                                    |  38%
label: countCorHeatmap (with options) 
List of 2
 $ fig.height: num 8
 $ fig.width : num 8

  |...............................................                                                               |  42%
  ordinary text without R code

  |...................................................                                                           |  46%
label: geneSampleHeatmap (with options) 
List of 2
 $ fig.height: num 12
 $ fig.width : num 6

  |.......................................................                                                       |  50%
  ordinary text without R code

  |...........................................................                                                   |  54%
label: unnamed-chunk-5
  |...............................................................                                               |  58%
label: BCV (with options) 
List of 2
 $ fig.height: num 5
 $ fig.width : num 6

  |....................................................................                                          |  62%
  ordinary text without R code

  |........................................................................                                      |  65%
label: unnamed-chunk-6
  |............................................................................                                  |  69%
  ordinary text without R code

  |................................................................................                              |  73%
label: unnamed-chunk-7
  |.....................................................................................                         |  77%
  ordinary text without R code

  |.........................................................................................                     |  81%
label: unnamed-chunk-8
  |.............................................................................................                 |  85%
  ordinary text without R code

  |.................................................................................................             |  88%
label: unnamed-chunk-9 (with options) 
List of 1
 $ echo: symbol F

**Quitting from lines 149-152 (/scratch_tmp/19940125/RtmpFkh6vQ/file5eb9168ca90c/Summary.spin.Rmd) 
Error: .onLoad failed in loadNamespace() for 'shiny', details:
  call: NULL
  error: invalid version specification '1,5'**
In addition: Warning messages:
1: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  span too small.   fewer data values than degrees of freedom.
2: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  pseudoinverse used at 0.47601
3: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  neighborhood radius 0.12605
4: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  reciprocal condition number  0
5: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  There are other near singularities as well. 0.0096078
6: In predLoess(object$y, object$x, newx = if (is.null(newdata)) object$x else if (is.data.frame(newdata)) as.matrix(model.frame(delete.response(terms(object)),  :
  span too small.   fewer data values than degrees of freedom.
7: In predLoess(object$y, object$x, newx = if (is.null(newdata)) object$x else if (is.data.frame(newdata)) as.matrix(model.frame(delete.response(terms(object)),  :
  pseudoinverse used at 0.47601
8: In predLoess(object$y, object$x, newx = if (is.null(newdata)) object$x else if (is.data.frame(newdata)) as.matrix(model.frame(delete.response(terms(object)),  :
  neighborhood radius 0.12605
9: In predLoess(object$y, object$x, newx = if (is.null(newdata)) object$x else if (is.data.frame(newdata)) as.matrix(model.frame(delete.response(terms(object)),  :
  reciprocal condition number  0
10: In predLoess(object$y, object$x, newx = if (is.null(newdata)) object$x else if (is.data.frame(newdata)) as.matrix(model.frame(delete.response(terms(object)),  :
  There are other near singularities as well. 0.0096078

Execution halted
```

**Comment by mumichae** [comment]
Hi,
thanks for the error  report. Unfortunately we couldn't reproduce the error on a newly setup system. What might be a possible issue are R packages that are already installed before that can cause incompatibilities. Could you please post the `sessionInfo()`?

**Comment by marcDabad** [comment]
What do you need I load into R session? Because now is like this:
```R

> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.7 (Santiago)

Matrix products: default
BLAS/LAPACK: ${HOME}/.conda/envs/drop/lib/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=ca_ES.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=ca_ES.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=ca_ES.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=ca_ES.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.4.0

loaded via a namespace (and not attached):
 [1] compiler_3.6.1  fastmap_1.0.1   magrittr_1.5    R6_2.4.0       
 [5] promises_1.1.0  later_1.0.0     htmltools_0.4.0 Rcpp_1.0.3     
 [9] digest_0.6.23   xtable_1.8-4    httpuv_1.5.2    mime_0.8       
[13] rlang_0.4.2 
```

**Comment by marcDabad** [comment]
What do you need I load into R session? Because I get this error running Snakemake pipeline. 

At this moment I get this:
```R
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.7 (Santiago)

Matrix products: default
BLAS/LAPACK:${HOME}/.conda/envs/drop/lib/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=ca_ES.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=ca_ES.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=ca_ES.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=ca_ES.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.1

```

**Comment by mumichae** [comment]
I see that you are using R in conda. This usually causes many issues and version incompatibilities, so I would not recommend it. Could you try using the system's version of R and see if you can reproduce the error?

**Comment by mumichae** [comment]
Hi @marcDabad ,
is this still an issue? Otherwise I would close this thread. We have also added some major improvements to the pipeline and the documentation, so make sure to check them out.

**Comment by marcDabad** [comment]
I tryied to reinstall it and I found that when I did:

drop demo
[...]
resource/dna_vcf/ALL.chr21.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.exome.vcf.gz
resource/hpo_genes.tsv.gz
Traceback (most recent call last):
  File "/usr/local/bin/drop", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/drop/cli.py", line 85, in demo
    dict_[key] = str(pathlib.Path(dict_[key]).resolve())
  File "/usr/lib/python3.8/pathlib.py", line 1033, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib/python3.8/pathlib.py", line 674, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.8/pathlib.py", line 658, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

But it's an other issue I guess.

**Comment by marcDabad** [comment]
It was a path error. 
It looks that this problem has been solved.
