### ISSUE TITLE
ImportError: cannot import name 'SNAKEFILE_CHOICES' from 'snakemake'

### ISSUE THREAD

**Issue by aojielian** [gagneurlab/drop#260]
After i installed drop with this command"conda create -n drop_env -c conda-forge -c bioconda drop" and then try drop demo, it will show these errors:
(drop_env) [a1lian@SKLMG10 ~]$ drop demo
Traceback (most recent call last):
  File "/zs32/home/a1lian/miniconda3/envs/drop_env/bin/drop", line 6, in <module>
    from drop.cli import main
  File "/zs32/home/a1lian/miniconda3/envs/drop_env/lib/python3.9/site-packages/drop/__init__.py", line 1, in <module>
    from .setupDrop import *
  File "/zs32/home/a1lian/miniconda3/envs/drop_env/lib/python3.9/site-packages/drop/setupDrop.py", line 2, in <module>
    from drop.config.DropConfig import DropConfig
  File "/zs32/home/a1lian/miniconda3/envs/drop_env/lib/python3.9/site-packages/drop/config/__init__.py", line 1, in <module>
    from .DropConfig import DropConfig
  File "/zs32/home/a1lian/miniconda3/envs/drop_env/lib/python3.9/site-packages/drop/config/DropConfig.py", line 1, in <module>
    from .SampleAnnotation import SampleAnnotation
  File "/zs32/home/a1lian/miniconda3/envs/drop_env/lib/python3.9/site-packages/drop/config/SampleAnnotation.py", line 1, in <module>
    from drop import utils
  File "/zs32/home/a1lian/miniconda3/envs/drop_env/lib/python3.9/site-packages/drop/utils.py", line 3, in <module>
    import wbuild
  File "/zs32/home/a1lian/miniconda3/envs/drop_env/lib/python3.9/site-packages/wbuild/__init__.py", line 10, in <module>
    from . import autolink
  File "/zs32/home/a1lian/miniconda3/envs/drop_env/lib/python3.9/site-packages/wbuild/autolink.py", line 6, in <module>
    from wbuild.utils import Config
  File "/zs32/home/a1lian/miniconda3/envs/drop_env/lib/python3.9/site-packages/wbuild/utils.py", line 12, in <module>
    from snakemake import get_argument_parser, parse_config, SNAKEFILE_CHOICES
ImportError: cannot import name 'SNAKEFILE_CHOICES' from 'snakemake' (/opt/tools/Python-3.6.1/lib/python3.6/site-packages/snakemake/__init__.py)

Please tell me what should i do?
Thanks 

Aojie

**Comment by mumichae** [comment]
Hi Aojie,

there seems to be another snakemake installation on Python 3.6 that is overshadowing your fresh DROP installation. Could you check if your `$PATH` might be the culprit and whether python and snakemake are taken from the same directory?

```
echo $PATH
which python
which snakemake
```

Hope this gets you closer to the root of the problem.

**Comment by aojielian** [comment]
Hi mumichae,
(base) [a1lian@SKLMG10 ~]$ echo $PATH
/zs32/home/a1lian/miniconda3/bin:/zs32/home/a1lian/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/opt/tools/seq-analysis/cufflinks-1.2.1.Linux_x86_64:/opt/tools/seq-analysis/tophat-2.1.0.Linux_x86_64:/opt/tools/seq-analysis/boost_1_60_0:/opt/tools/seq-analysis/liftover:/opt/tools/seq-analysis/bowtie2-2.2.6:/opt/tools/programming/ruby-2.2.3:/opt/tools/seq-analysis/annovar201602:/opt/tools/seq-analysis/MIPGEN:/opt/tools/seq-analysis/speedseq/bin:/opt/tools/seq-analysis/samtools-1.2:/opt/tools/seq-analysis/bwa-0.7.12:/opt/tools/R-3.2.2/bin:/usr/local/mysql/bin:/opt/tools/seq-analysis/PEAR-master/bin:/opt/tools/seq-analysis/freebayes/bamtools/bin:/opt/tools/seq-analysis/vcflib/bin:/opt/tools/msort:/opt/tools/repeatmasker/RepeatMasker:/opt/tools/seq-analysis/FastQC:/opt/tools/seq-analysis/fastx_toolkit_0.0.13/bin:/opt/tools/seq-analysis/vcftools_0.1.13/bin:/opt/tools/plink-1.07-x86_64:/opt/tools/sratoolkit.2.5.7-centos_linux64/bin:/opt/tools/seq-analysis/root-6.06.04/bin:/opt/tools/seq-analysis/CNVnator-0.3.2:/opt/tools/axel/bin:/opt/tools/xhmm:/opt/tools/Python-3.6.1/bin:/zs32/home/a1lian/.local/bin:/zs32/home/a1lian/bin


(base) [a1lian@SKLMG10 ~]$ which python
~/miniconda3/bin/python
(base) [a1lian@SKLMG10 ~]$ which snakemake
/opt/tools/Python-3.6.1/bin/snakemake


in my base environment, python and snakemake seems not in the same directory, But i create a new drop_env environment to run drop. 

(base) [a1lian@SKLMG10 ~]$ conda activate drop_env
(drop_env) [a1lian@SKLMG10 ~]$ which snakemake
~/miniconda3/envs/drop_env/bin/snakemake
(drop_env) [a1lian@SKLMG10 ~]$ which python
~/miniconda3/envs/drop_env/bin/python

**Comment by vyepez88** [comment]
Hi, it could be that because you anyway have snakemake in the base environment, the installation tries to use that instead of the one from the `drop_env` conda environment. Can you uninstall snakemake from base or have the base version of snakemake be the same as the drop version of snakemake?

**Comment by jfertaj** [comment]
I am facing a similar problem: 

```
File "/exports/igmm/eddie/tomlinson-eQTL/anaconda/envs/drop_env/lib/python3.12/site-packages/snakemake/cli.py", line 1893, in args_to_api
    dag_api = workflow_api.dag(
              ^^^^^^^^^^^^^^^^^
  File "/exports/igmm/eddie/tomlinson-eQTL/anaconda/envs/drop_env/lib/python3.12/site-packages/snakemake/api.py", line 326, in dag
    return DAGApi(
           ^^^^^^^
  File "<string>", line 6, in __init__
  File "/exports/igmm/eddie/tomlinson-eQTL/anaconda/envs/drop_env/lib/python3.12/site-packages/snakemake/api.py", line 436, in __post_init__
    self.workflow_api._workflow.dag_settings = self.dag_settings
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/exports/igmm/eddie/tomlinson-eQTL/anaconda/envs/drop_env/lib/python3.12/site-packages/snakemake/api.py", line 383, in _workflow
    workflow.include(
  File "/exports/igmm/eddie/tomlinson-eQTL/anaconda/envs/drop_env/lib/python3.12/site-packages/snakemake/workflow.py", line 1379, in include
    exec(compile(code, snakefile.get_path_or_uri(), "exec"), self.globals)
  File "/exports/eddie3_homes_local/jfernan2/drop_demo/Snakefile", line 3, in <module>
    import drop
  File "/exports/igmm/eddie/tomlinson-eQTL/anaconda/envs/drop_env/lib/python3.12/site-packages/drop/__init__.py", line 1, in <module>
    from .setupDrop import *
  File "/exports/igmm/eddie/tomlinson-eQTL/anaconda/envs/drop_env/lib/python3.12/site-packages/drop/setupDrop.py", line 2, in <module>
    from drop.config.DropConfig import DropConfig
  File "/exports/igmm/eddie/tomlinson-eQTL/anaconda/envs/drop_env/lib/python3.12/site-packages/drop/config/__init__.py", line 1, in <module>
    from .DropConfig import DropConfig
  File "/exports/igmm/eddie/tomlinson-eQTL/anaconda/envs/drop_env/lib/python3.12/site-packages/drop/config/DropConfig.py", line 1, in <module>
    from .SampleAnnotation import SampleAnnotation
  File "/exports/igmm/eddie/tomlinson-eQTL/anaconda/envs/drop_env/lib/python3.12/site-packages/drop/config/SampleAnnotation.py", line 1, in <module>
    from drop import utils
  File "/exports/igmm/eddie/tomlinson-eQTL/anaconda/envs/drop_env/lib/python3.12/site-packages/drop/utils.py", line 3, in <module>
    import wbuild
  File "/exports/igmm/eddie/tomlinson-eQTL/anaconda/envs/drop_env/lib/python3.12/site-packages/wbuild/__init__.py", line 10, in <module>
    from . import autolink
  File "/exports/igmm/eddie/tomlinson-eQTL/anaconda/envs/drop_env/lib/python3.12/site-packages/wbuild/autolink.py", line 6, in <module>
    from wbuild.utils import Config
  File "/exports/igmm/eddie/tomlinson-eQTL/anaconda/envs/drop_env/lib/python3.12/site-packages/wbuild/utils.py", line 12, in <module>
    from snakemake import get_argument_parser, parse_config, SNAKEFILE_CHOICES
ImportError: cannot import name 'get_argument_parser' from 'snakemake' (/exports/igmm/eddie/tomlinson-eQTL/anaconda/envs/drop_env/lib/python3.12/site-packages/snakemake/__init__.py)
```

I don't have any snakemake version installed in the base environment or any other environment

**Comment by AtaJadidAhari** [comment]
Hi @jfertaj seems like there is a compatibility issue with your version of snakemake. Can you downgrade snakemake to version 7 and check whether it solves the issue? 
You can try snakemake7.32.4 since it's already working fine for me.   ` mamba install -c conda-forge -c bioconda snakemake=7.32.4`  should do the trick. 

let us know if the issue is resolved!
