### ISSUE TITLE
Issue running the aberrant splicing module with the demo dataset.

### ISSUE THREAD

**Issue by lhomas** [gagneurlab/drop#268]
Hi Drop Team, I am trying to familiarise myself with drop using the test date set in preparation for using it with my own data but am having some trouble getting the test data set to work. I set up the drop demo as per the instructions in the documentation, but get the following error when running the aberrant expression module (mae and aberrant splicing run to completion). It might also be worth noting here that I have not been able to install drop using conda alone as it keeps freezing at the 'solving environment' step, so I have had to install it using pip and subsequently install required packages as error messages direct me to, so this may be an error on my part due to my dodgy computational practices, but I can't see anything obvious that indicates this. Cheers!

```
Load packages
There were 19 warnings (use warnings() to see them)
Loading required package: rtracklayer

Attaching package: ‘rtracklayer’

The following object is masked from ‘package:plotly’:
    export

Mon Nov  1 16:53:59 2021: Count split reads for sample: HG00096.1.M_111124_6_trunc
Error in stop_if(is.null(NCBI_assembly_info), "\"assembly_accession\" field in 'NCBI_LINKER' must ",  : 
  Error in UCSC genome registration file 'mm39.R':
  "assembly_accession" field in 'NCBI_LINKER' must be associated with a
  registered NCBI assembly
Calls: countSplitReads ... registered_UCSC_genomes -> lapply -> lapply -> FUN -> stop_if
Execution halted
[Mon Nov  1 16:53:59 2021]
Error in rule AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R:
    jobid: 59
    output: /home/neuro/Documents/Thomas/drop_demo/Output/processed_data/aberrant_splicing/datasets/cache/raw-fraser/sample_tmp/splitCounts/sample_HG00096.1.M_111124_6_trunc.done
    log: /home/neuro/Documents/Thomas/drop_demo/.drop/tmp/AS/fraser/splitReads/HG00096.1.M_111124_6_trunc.Rds (check log file(s) for error message)

Traceback (most recent call last):
  File "/home/neuro/miniconda3/envs/drop_env/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 593, in _callback
    raise ex
  File "/home/neuro/miniconda3/envs/drop_env/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/neuro/miniconda3/envs/drop_env/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 579, in cached_or_run
    run_func(*args)
  File "/home/neuro/miniconda3/envs/drop_env/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2460, in run_wrapper
    raise ex
  File "/home/neuro/miniconda3/envs/drop_env/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2417, in run_wrapper
    run(
  File "/tmp/tmpj36c87xm", line 340, in __rule_AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R
    input: "Scripts/AberrantSplicing/pipeline/aberrant_splicing_readme.md"
  File "/home/neuro/miniconda3/envs/drop_env/lib/python3.9/site-packages/snakemake/script.py", line 1369, in script
    executor.evaluate()
  File "/home/neuro/miniconda3/envs/drop_env/lib/python3.9/site-packages/snakemake/script.py", line 381, in evaluate
    self.execute_script(fd.name, edit=edit)
  File "/home/neuro/miniconda3/envs/drop_env/lib/python3.9/site-packages/snakemake/script.py", line 716, in execute_script
    self._execute_cmd("Rscript --vanilla {fname:q}", fname=fname)
  File "/home/neuro/miniconda3/envs/drop_env/lib/python3.9/site-packages/snakemake/script.py", line 414, in _execute_cmd
    return shell(
  File "/home/neuro/miniconda3/envs/drop_env/lib/python3.9/site-packages/snakemake/shell.py", line 265, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  Rscript --vanilla /home/neuro/Documents/Thomas/drop_demo/.snakemake/scripts/tmprir5qn85.01_1_countRNA_splitReads_samplewise.R' returned non-zero exit status 1.

```

**Comment by nickhsmith** [comment]
Thanks for letting us know. I'm curious, ~can you tell me how you installed DROP~ can you try using mamba instead (`mamba create -n drop_env -c conda-forge -c bioconda drop`) 

This seems like an error in the R function when looking at the genome file. And I'm curious if using the conda install or running it in a different environment could fix it


Could you also please share your config? The genome registration file mm39.R makes me think you somehow are using a mouse genome instead of hg19.

Thanks

**Comment by lhomas** [comment]
Thanks for getting back to me.

Installing with mamba did the trick, got it sorted pretty easily and now the demo runs without issue.

**Comment by vyepez88** [comment]
great to hear that @lhomas!
