### ISSUE TITLE
Issue in exploring outlier results and a query about plotting

### ISSUE THREAD

**Issue by ChiaraF32** [gagneurlab/drop#276]
**Description of dataset:** I am trialling DROP on a set of 27 RNAseq files generated from Muscle tissue. I did not perform the alignment step myself to generate the BAM files, but I am aware that they have been aligned to hg19 and contain paired end but not strand specific read data. The data has been generated and processed across 3 years so I am not sure if it has all been processed uniformly.

**Environment:** For context, I have set-up DROP within a cloud-based Ubuntu 18.04 virtual machine with 16 CPU and 64 GB of RAM. I ran the drop_demo before trialling DROP on my own data, and it ran to completion without issues, suggesting the environment has been set up suitably. 

**Description of issue:** have had success with running the aberrant expression and aberrant splicing modules individually, and have explored the outputs. Both look to be working well, except there were no expression outliers called, which I assume is because of the small sample size. I went to run DROP to explore the outlier results (using snakemake –cores 10), but the pipeline crashed very early on, and output the following error message:

`[Thu Nov 18 05:59:41 2021]
Error in rule AberrantExpression_Overview_R:
    jobid: 141
    output: /data/drop/pathwest2/output/html/Scripts_AberrantExpression_Overview.html
    log: /data/drop/pathwest2/.drop/tmp/AE/Overview.Rds (check log file(s) for error message)

Traceback (most recent call last):
  File "/data/miniconda3/envs/drop_env/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 593, in _callback
    raise ex
  File "/data/miniconda3/envs/drop_env/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/data/miniconda3/envs/drop_env/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 579, in cached_or_run
    run_func(*args)
  File "/data/miniconda3/envs/drop_env/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2461, in run_wrapper
    raise ex
  File "/data/miniconda3/envs/drop_env/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2418, in run_wrapper
    run(
  File "/tmp/tmpiiae210h", line 24, in __rule_AberrantExpression_Overview_R
    log: snakemake = str(tmp_dir / "AE" / "{annotation}" / "{dataset}" / "count_summary.Rds")
  File "/data/miniconda3/envs/drop_env/lib/python3.9/site-packages/snakemake/script.py", line 1371, in script
    executor.evaluate()
  File "/data/miniconda3/envs/drop_env/lib/python3.9/site-packages/snakemake/script.py", line 381, in evaluate
    self.execute_script(fd.name, edit=edit)
  File "/data/miniconda3/envs/drop_env/lib/python3.9/site-packages/snakemake/script.py", line 718, in execute_script
    self._execute_cmd("Rscript --vanilla {fname:q}", fname=fname)
  File "/data/miniconda3/envs/drop_env/lib/python3.9/site-packages/snakemake/script.py", line 414, in _execute_cmd
    return shell(
  File "/data/miniconda3/envs/drop_env/lib/python3.9/site-packages/snakemake/shell.py", line 266, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  Rscript --vanilla /data/drop/pathwest2/.snakemake/scripts/tmpbyorbb0n.wBRender.R' returned non-zero exit status 1.
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message`

Could you please help me troubleshoot what has gone wrong?

I also have a query relating to plot generation using FRASER. In FRASER you can make QQ plots for a single junction using `plotQQ(fds, result=res[1])`. I find this format limiting if you don't know what res[value] the result you want to plot corresponds to in the data. Is there an easy way of searching this by the sample ID and gene?

Thanks so much

**Comment by vyepez88** [comment]
Hi, the Overview script afterwards is to instruct users how to plot individual results. In your case, there weren't, so it cannot plot anything and returns an error. But anyway, your pipeline ran through.
Regarding the second question, you can subset the results by sample ID and gene doing:
`res[sampleID == my_input_sample & hgncSymbol == my_input_gene]`

**Comment by nickhsmith** [comment]
Is this issue solved?

**Comment by ChiaraF32** [comment]
Yes! Apologies, I forgot to follow-up. Thanks for your help.
