### ISSUE TITLE
Unable to update conda environment

### ISSUE THREAD

**Issue by SophieS9** [gagneurlab/drop#367]
Hi Drop Team!

I have version 1.0.5 installed, which worked with the demo run but I'm now having problems with my own data. I thought I'd try updating the version, incase that's the issue, however my conda environment won't update. 

Here's the command I'm running:
`conda update drop`

Nothing else is installed in this environment, it's for drop only. 

Here's the traceback (just the end when it starts to fail):
```
Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: / WARNING conda.core.link:run_script(1202): pre-unlink script failed for package bioconda/noarch::bioconductor-genomeinfodbdata-1.2.6-r41hdfd78af_0
consider notifying the package maintainer                                                                          \ b''                                                                                                                - b''                                                                                                                / b''                                                                                                                done
ERROR conda.core.link:_execute(698): An error occurred while installing package 'bioconda::bioconductor-genomeinfodbdata-1.2.7-r41hdfd78af_2'.
Rolling back transaction: done
class: LinkError
message:
post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.7-r41hdfd78af_2
location of failed script: /home/v.so257591/.conda/envs/drop_rna/bin/.bioconductor-genomeinfodbdata-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: /home/v.so257591/.conda/envs/drop_rna/share/bioconductor-genomeinfodbdata-1.2.7-2/GenomeInfoDbData_1.2.7.tar.gz: FAILED
/home/v.so257591/.conda/envs/drop_rna/share/bioconductor-genomeinfodbdata-1.2.7-2/GenomeInfoDbData_1.2.7.tar.gz: FAILED
ERROR: post-link.sh was unable to download any of the following URLs with the md5sum 74c82f26111062a9ceb3c5331088cd56:
https://bioconductor.org/packages/3.14/data/annotation/src/contrib/GenomeInfoDbData_1.2.7.tar.gz
https://bioarchive.galaxyproject.org/GenomeInfoDbData_1.2.7.tar.gz
https://depot.galaxyproject.org/software/bioconductor-genomeinfodbdata/bioconductor-genomeinfodbdata_1.2.7_src_all.tar.gz

stderr:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   416  100   416    0     0     72      0  0:00:05  0:00:05 --:--:--    83
 31 10.6M   31 3436k    0     0  28489      0  0:06:32  0:02:03  0:04:29 27427
curl: (18) transfer closed with 7674210 bytes remaining to read
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   153  100   153    0     0     20      0  0:00:07  0:00:07 --:--:--    37
md5sum: WARNING: 1 computed checksum did NOT match
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   153  100   153    0     0     26      0  0:00:05  0:00:05 --:--:--    31
md5sum: WARNING: 1 computed checksum did NOT match

return code: 1

kwargs:
{}

Traceback (most recent call last):
  File "/Apps/wren/anaconda/3/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "/Apps/wren/anaconda/3/lib/python3.8/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/Apps/wren/anaconda/3/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
    return getattr(module, func_name)(args, parser)
  File "/Apps/wren/anaconda/3/lib/python3.8/site-packages/conda/cli/main_update.py", line 20, in execute
    install(args, parser, 'update')
  File "/Apps/wren/anaconda/3/lib/python3.8/site-packages/conda/cli/install.py", line 317, in install
    handle_txn(unlink_link_transaction, prefix, args, newenv)
  File "/Apps/wren/anaconda/3/lib/python3.8/site-packages/conda/cli/install.py", line 346, in handle_txn
    unlink_link_transaction.execute()
  File "/Apps/wren/anaconda/3/lib/python3.8/site-packages/conda/core/link.py", line 249, in execute
    self._execute(tuple(concat(interleave(itervalues(self.prefix_action_groups)))))
  File "/Apps/wren/anaconda/3/lib/python3.8/site-packages/conda/core/link.py", line 712, in _execute
    raise CondaMultiError(tuple(concatv(
conda.CondaMultiErrorclass: LinkError
message:
post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.7-r41hdfd78af_2
location of failed script: /home/v.so257591/.conda/envs/drop_rna/bin/.bioconductor-genomeinfodbdata-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: /home/v.so257591/.conda/envs/drop_rna/share/bioconductor-genomeinfodbdata-1.2.7-2/GenomeInfoDbData_1.2.7.tar.gz: FAILED
/home/v.so257591/.conda/envs/drop_rna/share/bioconductor-genomeinfodbdata-1.2.7-2/GenomeInfoDbData_1.2.7.tar.gz: FAILED
ERROR: post-link.sh was unable to download any of the following URLs with the md5sum 74c82f26111062a9ceb3c5331088cd56:
https://bioconductor.org/packages/3.14/data/annotation/src/contrib/GenomeInfoDbData_1.2.7.tar.gz
https://bioarchive.galaxyproject.org/GenomeInfoDbData_1.2.7.tar.gz
https://depot.galaxyproject.org/software/bioconductor-genomeinfodbdata/bioconductor-genomeinfodbdata_1.2.7_src_all.tar.gz

stderr:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   416  100   416    0     0     72      0  0:00:05  0:00:05 --:--:--    83
 31 10.6M   31 3436k    0     0  28489      0  0:06:32  0:02:03  0:04:29 27427
curl: (18) transfer closed with 7674210 bytes remaining to read
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   153  100   153    0     0     20      0  0:00:07  0:00:07 --:--:--    37
md5sum: WARNING: 1 computed checksum did NOT match
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   153  100   153    0     0     26      0  0:00:05  0:00:05 --:--:--    31
md5sum: WARNING: 1 computed checksum did NOT match

return code: 1

kwargs:
{}

: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Apps/wren/anaconda/3/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/Apps/wren/anaconda/3/lib/python3.8/site-packages/conda/cli/main.py", line 150, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "/Apps/wren/anaconda/3/lib/python3.8/site-packages/conda/exceptions.py", line 1371, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/Apps/wren/anaconda/3/lib/python3.8/site-packages/conda/exceptions.py", line 1082, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/Apps/wren/anaconda/3/lib/python3.8/site-packages/conda/exceptions.py", line 1113, in handle_exception
    return self.handle_application_exception(exc_val, exc_tb)
  File "/Apps/wren/anaconda/3/lib/python3.8/site-packages/conda/exceptions.py", line 1129, in handle_application_exception
    self._print_conda_exception(exc_val, exc_tb)
  File "/Apps/wren/anaconda/3/lib/python3.8/site-packages/conda/exceptions.py", line 1133, in _print_conda_exception
    print_conda_exception(exc_val, exc_tb)
  File "/Apps/wren/anaconda/3/lib/python3.8/site-packages/conda/exceptions.py", line 1056, in print_conda_exception
    stderrlog.error("\n%r\n", exc_val)
  File "/Apps/wren/anaconda/3/lib/python3.8/logging/__init__.py", line 1463, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/Apps/wren/anaconda/3/lib/python3.8/logging/__init__.py", line 1577, in _log
    self.handle(record)
  File "/Apps/wren/anaconda/3/lib/python3.8/logging/__init__.py", line 1586, in handle
    if (not self.disabled) and self.filter(record):
  File "/Apps/wren/anaconda/3/lib/python3.8/logging/__init__.py", line 807, in filter
    result = f.filter(record)
  File "/Apps/wren/anaconda/3/lib/python3.8/site-packages/conda/gateways/logging.py", line 60, in filter
    record.msg = record.msg % new_args
  File "/Apps/wren/anaconda/3/lib/python3.8/site-packages/conda/__init__.py", line 126, in __repr__
    errs.append(e.__repr__())
  File "/Apps/wren/anaconda/3/lib/python3.8/site-packages/conda/__init__.py", line 65, in __repr__
    return '%s: %s' % (self.__class__.__name__, text_type(self))
  File "/Apps/wren/anaconda/3/lib/python3.8/site-packages/conda/__init__.py", line 84, in __str__
    return text_type(self.message % self._kwargs)
ValueError: unsupported format character 'T' (0x54) at index 928
```

Any ideas? 

Thanks!

**Comment by vyepez88** [comment]
Hi Sophie,
Executing `drop update` will simply update your analysis repositories with the latest DROP scripts. In your case, first you need to reinstall it using: `mamba install -c bioconda drop` in your dedicated drop environment. Then you can execute `drop update` in your analysis repository. Let us know if it worked.

**Comment by SophieS9** [comment]
Hi @vyepez88 thanks for the super speedy response. I ran those commands (apart from using conda instead of mamba) and I'm still showing as version 1.0.5? See below!

```
(drop_rna) [v.so257591@ch2 Drop]$ conda install -c bioconda drop
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.3
  latest version: 4.14.0

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/v.so257591/.conda/envs/drop_rna

  added / updated specs:
    - drop


The following packages will be UPDATED:

  ca-certificates                      2021.5.30-ha878542_0 --> 2022.6.15-ha878542_0
  certifi            conda-forge/linux-64::certifi-2021.5.~ --> conda-forge/noarch::certifi-2022.6.15-pyhd8ed1ab_1


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(drop_rna) [v.so257591@ch2 Drop]$ drop update
updating local Scripts if necessary
update...done
(drop_rna) [v.so257591@ch2 Drop]$ drop --version
drop, version 1.0.5
```

**Comment by vyepez88** [comment]
I see. Try removing your conda environment and recreate it and reinstall DROP from scratch:
`mamba create -n drop_rna -c conda-forge -c bioconda drop --override-channels`
Then execute `drop update`.
Keep me updated.

**Comment by SophieS9** [comment]
That worked! Thanks :) Hopefully fixes my other problem too, or you might be hearing back from me!

**Comment by vyepez88** [comment]
Hopefully! Keep us updated also if it worked! :)

**Comment by SophieS9** [comment]
Upgrading fixed my issue :) thanks @vyepez88
