### ISSUE TITLE
ImportError: cannot import name 'get_argument_parser' from 'snakemake' 

### ISSUE THREAD

**Issue by sgomes-catarina** [gagneurlab/drop#505]
Hi,
After installing drop version 1.3.3 with mamba I'm getting the following error:

```
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/drop_env_v1.3.3/bin/drop", line 5, in <module>
    from drop.cli import main
  File "/home/ubuntu/miniconda3/envs/drop_env_v1.3.3/lib/python3.12/site-packages/drop/__init__.py", line 1, in <module>
    from .setupDrop import *
  File "/home/ubuntu/miniconda3/envs/drop_env_v1.3.3/lib/python3.12/site-packages/drop/setupDrop.py", line 2, in <module>
    from drop.config.DropConfig import DropConfig
  File "/home/ubuntu/miniconda3/envs/drop_env_v1.3.3/lib/python3.12/site-packages/drop/config/__init__.py", line 1, in <module>
    from .DropConfig import DropConfig
  File "/home/ubuntu/miniconda3/envs/drop_env_v1.3.3/lib/python3.12/site-packages/drop/config/DropConfig.py", line 1, in <module>
    from .SampleAnnotation import SampleAnnotation
  File "/home/ubuntu/miniconda3/envs/drop_env_v1.3.3/lib/python3.12/site-packages/drop/config/SampleAnnotation.py", line 1, in <module>
    from drop import utils
  File "/home/ubuntu/miniconda3/envs/drop_env_v1.3.3/lib/python3.12/site-packages/drop/utils.py", line 3, in <module>
    import wbuild
  File "/home/ubuntu/miniconda3/envs/drop_env_v1.3.3/lib/python3.12/site-packages/wbuild/__init__.py", line 10, in <module>
    from . import autolink
  File "/home/ubuntu/miniconda3/envs/drop_env_v1.3.3/lib/python3.12/site-packages/wbuild/autolink.py", line 6, in <module>
    from wbuild.utils import Config
  File "/home/ubuntu/miniconda3/envs/drop_env_v1.3.3/lib/python3.12/site-packages/wbuild/utils.py", line 12, in <module>
    from snakemake import get_argument_parser, parse_config, SNAKEFILE_CHOICES
ImportError: cannot import name 'get_argument_parser' from 'snakemake' (/home/ubuntu/miniconda3/envs/drop_env_v1.3.3/lib/python3.12/site-packages/snakemake/__init__.py)
```

The output for `which python` and `which snakemake` are:

```
/home/ubuntu/miniconda3/envs/drop_env_v1.3.3/bin/python
/home/ubuntu/miniconda3/envs/drop_env_v1.3.3/bin/snakemake
```

The python version is 3.12.1 and snakemake is 8.0.1. I do not have snakemake installed in my base environment.

**Comment by drewjbeh** [comment]
Hi there,

Wondering if this is a mamba issue. Please see #509 and try the solution mentioned there by installing using the yml file. This is also detailed in the README. In the meantime I will look into potential issues with using mamba

**Comment by vyepez88** [comment]
Hi @sgomes-catarina, were you able to check this?

**Comment by AtaJadidAhari** [comment]
Hi @sgomes-catarina, any updates on this? I believe the issue is resolved in DROP v1.3.4 and later versions, since we restricted snakemake version to be < 8.0.0
