### ISSUE TITLE
micromamba snakemake import error

### ISSUE THREAD

**Issue by akhilvelluva** [gagneurlab/drop#506]
I got error while running demo after the drop install using this command 
micromamba create -n drop_env -c conda-forge -c bioconda drop --override-channels

My path
echo $PATH
/home/akhil/micromamba/envs/drop_env/bin:/condabin:/software/anaconda3/2021.05/bin:/software/micromamba/1.4.9/bin:/opt/lsf/10.1/linux3.10-glibc2.17-x86_64/etc:/opt/lsf/10.1/linux3.10-glibc2.17-x86_64/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/lsf-shared/bin:/software/bin

which python

~/micromamba/envs/drop_env/bin/python

which snakemake

~/micromamba/envs/drop_env/bin/snakemake

drop demo
Traceback (most recent call last):
  File "/home/akhil/micromamba/envs/drop_env/bin/drop", line 6, in <module>
    from drop.cli import main
  File "/home/akhil/micromamba/envs/drop_env/lib/python3.12/site-packages/drop/__init__.py", line 1, in <module>
    from .setupDrop import *
  File "/home/akhil/micromamba/envs/drop_env/lib/python3.12/site-packages/drop/setupDrop.py", line 2, in <module>
    from drop.config.DropConfig import DropConfig
  File "/home/akhil/micromamba/envs/drop_env/lib/python3.12/site-packages/drop/config/__init__.py", line 1, in <module>
    from .DropConfig import DropConfig
  File "/home/akhil/micromamba/envs/drop_env/lib/python3.12/site-packages/drop/config/DropConfig.py", line 1, in <module>
    from .SampleAnnotation import SampleAnnotation
  File "/home/akhil/micromamba/envs/drop_env/lib/python3.12/site-packages/drop/config/SampleAnnotation.py", line 1, in <module>
    from drop import utils
  File "/home/akhil/micromamba/envs/drop_env/lib/python3.12/site-packages/drop/utils.py", line 3, in <module>
    import wbuild
  File "/home/akhil/micromamba/envs/drop_env/lib/python3.12/site-packages/wbuild/__init__.py", line 10, in <module>
    from . import autolink
  File "/home/akhil/micromamba/envs/drop_env/lib/python3.12/site-packages/wbuild/autolink.py", line 6, in <module>
    from wbuild.utils import Config
  File "/home/akhil/micromamba/envs/drop_env/lib/python3.12/site-packages/wbuild/utils.py", line 12, in <module>
    from snakemake import get_argument_parser, parse_config, SNAKEFILE_CHOICES
ImportError: cannot import name 'get_argument_parser' from 'snakemake' (/home/akhil/micromamba/envs/drop_env/lib/python3.12/site-packages/snakemake/__init__.py)

both python and snakemake loaded from same directory and how to resolve this ?

**Comment by akhilvelluva** [comment]
fixed using the yaml file

**Comment by akhilvelluva** [comment]
fixed using the yaml file

**Comment by vyepez88** [comment]
Hi, sorry for the late reply, I was trying to google your error but couldn't find anything. Thanks also for reporting the solution!
